# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
