# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0002_speaker_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
