# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0003_auto_20170425_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scope.Speaker'),
        ),
    ]
