# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0005_auto_20170426_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='social',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
